name: Periodic Workflow

on:
  schedule:
    - cron: '35 12 * * *' # Run the workflow every day at 2 AM (UTC)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Run Your Commands
        run: |
          "Hello World"
